<div class="row">
	<div class="col-md-12">
        <p><a href="#/home">Home</a> &gt; <a href="#/home/federation">Federation</a> &gt; <strong>Donation to {{memberId}}</strong></p>
		<table class="table table-condensed table-striped">
    		<thead>
    			<tr>
    				<th>Federation identity</th>
    				<th>Consumed (FCU*min)</th>
    			</tr>
    		</thead>
    		<tbody>
    			<tr ng-repeat="use in memberUsers">
    				<td>{{use.user}}</td>
    				<td>{{use.usage}}</td>
    			</tr>
    		</tbody>
    	</table>
	</div>
</div>