<div class="row">
	<div class="col-md-12">
		<!-- Nav tabs -->
		<ul class="mytabs nav nav-tabs" role="tablist">
			<li role="presentation" class="active"><a href="#localuserstab" aria-controls="localuserstab" role="tab" data-toggle="tab">Local Users</a></li>
		    <li role="presentation"><a href="#memberstab" aria-controls="memberstab" role="tab" data-toggle="tab">Members</a></li>
		</ul>

		<!-- Tab panes -->
		<div class="tab-content">
			<div role="tabpanel" class="tab-pane active" id="localuserstab">
				<h2>Local Users</h2>
				<table class="table table-condensed table-striped">
		    		<thead>
		    			<tr>
		    				<th>Federation user</th>
		    				<th>Consumed</th>
		    			</tr>
		    		</thead>
		    		<tbody>
		    			<tr ng-repeat="use in usage">
		    				<td><a href="#/usage/user/{{use.federation_user}}">{{use.federation_user}}</a></td>
		    				<td>{{use.value}}</td>
		    			</tr>
		    		</tbody>
		    	</table>
			</div>
		    <div role="tabpanel" class="tab-pane" id="memberstab">
		    	<h3>Members</h3>
		    	<table class="table table-condensed table-striped">
		    		<thead>
		    			<tr>
		    				<th>Member ID</th>
		    				<th>Donated</th>
		    				<th>Consumed</th>
		    				<th>Debit</th>
		    			</tr>
		    		</thead>
		    		<tbody>
		    			<tr ng-repeat="member in members">
		    				<td>{{member.memberId}}</td>
		    				<td>{{member.donated}}</td>
		    				<td>{{member.consumed}}</td>
		    				<td>{{member.debit}}</td>
		    			</tr>
		    		</tbody>
		    	</table>
		    </div>
		</div>
	</div>
</div>