<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<form class="form-signin" ng-submit="validateLogin()">
	        <h2 class="form-signin-heading">Please sign in</h2>
	        <div class="form-group">
	        	<textarea id="authToken" ng-model="authToken" cols="40" rows="10" class="form-control" placeholder="Auth Token" name="authToken" required autofocus></textarea>
	        </div>
	        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
	    </form>
	</div>
</div>